name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "Dockerfile"
            jenkins_version: "2.492.3"
            tags: [ "spryker/jenkins-boilerplate:${{ matrix.jenkins_version }}", "spryker/jenkins-boilerplate:latest" ]
            platforms: [ "linux/amd64", "linux/arm64" ]

          - image: "Dockerfile"
            jenkins_version: "2.504.1"
            tags: [ "spryker/jenkins-boilerplate:${{ matrix.jenkins_version }}" ]
            platforms: [ "linux/amd64", "linux/arm64" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
          build-args: |
            JENKINS_VERSION=${{ join(matrix.jenkins_version) }}
